name: Build and Deploy app for production

on:
  push:
    branches:
      - main
    paths:
      - firebase.json
      - packages/app/**
      - "!packages/app/package.json"

jobs:
  build-deploy:
    name: Build and Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn workspace @yukukuru/app lint

      - name: Run build
        run: yarn workspace @yukukuru/app build
        env:
          NEXT_APP_PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          NEXT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NEXT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          NEXT_APP_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          NEXT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          NEXT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Install to firebase-tools
        run: npm i -g firebase-tools

      - name: Add target to Firebase
        run: npx firebase target:apply hosting app $SITE_ID --project $PROJECT_ID
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          SITE_ID: ${{ secrets.FIREBASE_HOSTING_APP_SITE_ID }}

      - name: Deploy to Firebase
        run: npx firebase deploy --only hosting:app --project $PROJECT_ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
