name: Build and Deploy firestore for production

on:
  push:
    branches:
      - main
    paths:
      - firebase.json
      - firestore.indexes.json
      - firestore.rules

jobs:
  build-deploy:
    name: Build and Deploy firestore
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install to firebase-tools
        run: npm i -g firebase-tools

      - name: Deploy to Firebase
        run: npx firebase deploy -f --only firestore --project $PROJECT_ID
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
