name: Build and Deploy firestore for develop

on:
  push:
    branches:
      - develop
    paths:
      - firebase.json
      - firestore.indexes.json
      - firestore.rules

jobs:
  build-deploy:
    name: Build and Deploy firestore
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install to firebase-tools
        run: npm i -g firebase-tools

      - name: Deploy to Firebase
        run: npx firebase deploy --only firestore --project $PROJECT_ID
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_DEVELOP }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
