name: Test types

on:
  pull_request:
    paths:
    - 'packages/types/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run lint
      run: yarn workspace @yukukuru/types lint
