name: Test Admin App

on:
  pull_request:
    paths:
      - packages/admin-app/**

jobs:
  test:
    name: Test Admin App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run format
        run: yarn workspace @yukukuru/admin-app format

      - name: Run lint
        run: yarn workspace @yukukuru/admin-app lint

      - name: Run build
        run: yarn workspace @yukukuru/admin-app build
