name: Test functions

on:
  pull_request:
    paths:
      - packages/functions/**

jobs:
  test:
    name: Test functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install dependencies on functions
        run: yarn --frozen-lockfile
        working-directory: packages/functions

      - name: Run lint
        run: yarn lint
        working-directory: packages/functions

      - name: Run build
        run: yarn build
        working-directory: packages/functions
